from pathlib import Path

DATA_PROC_BASE_DIR = Path(__file__).parent
OUTPUT_TRANSCRIPT = DATA_PROC_BASE_DIR / "Transcript"
HTML_OUTPUT_FOLDER = DATA_PROC_BASE_DIR / "HTML"

RAW_VIDEO_FOLDER = DATA_PROC_BASE_DIR / "VIDEO_1RawData"
SPLITTED_VIDEO_FOLDER = DATA_PROC_BASE_DIR / "VIDEO_2Splitted"

RAW_AUDIO_FOLDER = DATA_PROC_BASE_DIR / "AUDIO_1RawData"
SPLITTED_AUDIO_FOLDER = DATA_PROC_BASE_DIR / "AUDIO_2Splitted"
ENHANCED_AUDIO_FOLDER = DATA_PROC_BASE_DIR / "AUDIO_3Enhanced"


folders = [OUTPUT_TRANSCRIPT, HTML_OUTPUT_FOLDER   ,
           RAW_VIDEO_FOLDER , SPLITTED_VIDEO_FOLDER,
           RAW_AUDIO_FOLDER , SPLITTED_AUDIO_FOLDER, ENHANCED_AUDIO_FOLDER]

for folder in folders:
    folder.mkdir(parents=True, exist_ok=True)

VIDEO_EXTENSIONS = (".mp4", ".mov", ".3gp", ".avi", ".mkv")
AUDIO_EXTENSIONS = (".mp3", ".wav", ".m4a")
